############################################
# Windows
############################################
name: GameEngine Build Check
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: echo "Job will start due to ${{ github.event_name }} event."
      - run: echo "Job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Start building the trunk..."
      - run: |
          call build.bat
          if ($errorlevel -ne 0){exit $errorlevel}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}."
